apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.namePrefix }}-external
  labels:
{{ include "deepgram-self-hosted.labels" . | indent 4}}
    app: {{ .Values.api.namePrefix }}
    {{- range $key, $val := .Values.api.additionalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
  {{- if and (eq .Values.api.service.type "LoadBalancer") .Values.api.service.annotations }}
  annotations:
    {{- range $key, $val := .Values.api.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
  {{- end }}
spec:
  selector:
    app: {{ .Values.api.namePrefix }}
    {{ include "deepgram-self-hosted.selectorLabels" . }}
  type: {{ .Values.api.service.type | default "ClusterIP" }}
  {{- if and (eq .Values.api.service.type "LoadBalancer") .Values.api.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- range .Values.api.service.loadBalancerSourceRanges }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- if and (eq .Values.api.service.type "LoadBalancer") .Values.api.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.api.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: "primary"
      port: {{ .Values.api.server.port }}
      targetPort: {{ .Values.api.server.port }}

