apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.namePrefix }}-external
  labels:
{{ include "deepgram-self-hosted.labels" . | indent 4}} 
    {{- range $key, $val := .Values.engine.additionalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
spec:
  selector:
    app: deepgram-api
    {{ include "deepgram-self-hosted.selectorLabels" . }} 
  type: NodePort
  ports:
    - name: "primary"
      port: {{ .Values.api.server.port }}
      targetPort: {{ .Values.api.server.port }}

