apiVersion: v2
name: deepgram-self-hosted
type: application
version: 0.1.0
appVersion: "release-240426"
description: A Helm chart for running Deepgram services in a self-hosted environment
home: "https://developers.deepgram.com/docs/on-prem-introduction"
maintainers:
  - email: brent.george@deepgram.com
    name: Brent George
sources: ["https://github.com/deepgram/helm-charts"]
kubeVersion: ">=1.19.0-0"

dependencies:
  - name: gpu-operator
    version: "^24.3.0"
    repository: "https://helm.ngc.nvidia.com/nvidia"
    condition: gpu-operator.enabled
