apiVersion: v1
entries:
  cluster-autoscaler:
  - apiVersion: v2
    appVersion: 1.30.0
    created: "2024-07-05T12:27:38.293500858-07:00"
    description: Scales Kubernetes worker nodes within autoscaling groups.
    digest: 38fa4bde60e5ca26bdecdbb980546b1f036f331123c63e0079c459d882d7a783
    home: https://github.com/kubernetes/autoscaler
    icon: https://github.com/kubernetes/kubernetes/raw/master/logo/logo.png
    maintainers:
    - email: guyjtempleton@googlemail.com
      name: gjtempleton
    name: cluster-autoscaler
    sources:
    - https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler
    type: application
    urls:
    - charts/cluster-autoscaler-9.37.0.tgz
    version: 9.37.0
  gpu-operator:
  - apiVersion: v2
    appVersion: v24.3.0
    created: "2024-07-05T12:27:38.295688731-07:00"
    dependencies:
    - condition: nfd.enabled
      name: node-feature-discovery
      repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      version: v0.15.4
    description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
    digest: ca3ad7585046897a772f0faf664a1538309886c5687f4652520752f428f0987e
    home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
    icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
    keywords:
    - gpu
    - cuda
    - compute
    - operator
    - deep learning
    - monitoring
    - tesla
    kubeVersion: '>= 1.16.0-0'
    name: gpu-operator
    sources:
    - https://github.com/NVIDIA/gpu-operator
    urls:
    - charts/gpu-operator-v24.3.0.tgz
    version: v24.3.0
  kube-prometheus-stack:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/prometheus-community/helm-charts
        - name: Upstream Project
          url: https://github.com/prometheus-operator/kube-prometheus
      artifacthub.io/operator: "true"
    apiVersion: v2
    appVersion: v0.74.0
    created: "2024-07-05T12:27:38.317888042-07:00"
    dependencies:
    - condition: crds.enabled
      name: crds
      repository: ""
      version: 0.0.0
    - condition: kubeStateMetrics.enabled
      name: kube-state-metrics
      repository: https://prometheus-community.github.io/helm-charts
      version: 5.20.*
    - condition: nodeExporter.enabled
      name: prometheus-node-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 4.36.*
    - condition: grafana.enabled
      name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 8.0.*
    - condition: windowsMonitoring.enabled
      name: prometheus-windows-exporter
      repository: https://prometheus-community.github.io/helm-charts
      version: 0.3.*
    description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards,
      and Prometheus rules combined with documentation and scripts to provide easy
      to operate end-to-end Kubernetes cluster monitoring with Prometheus using the
      Prometheus Operator.
    digest: 4ca23fb412c04b51c2dfe89254e910dcae3575b568e8ac84d126c186f91df3af
    home: https://github.com/prometheus-operator/kube-prometheus
    icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
    keywords:
    - operator
    - prometheus
    - kube-prometheus
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - email: andrew@quadcorps.co.uk
      name: andrewgkew
    - email: gianrubio@gmail.com
      name: gianrubio
    - email: github.gkarthiks@gmail.com
      name: gkarthiks
    - email: kube-prometheus-stack@sisti.pt
      name: GMartinez-Sisti
    - email: github@jkroepke.de
      name: jkroepke
    - email: scott@r6by.com
      name: scottrigby
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    - email: quentin.bisson@gmail.com
      name: QuentinBisson
    name: kube-prometheus-stack
    sources:
    - https://github.com/prometheus-community/helm-charts
    - https://github.com/prometheus-operator/kube-prometheus
    type: application
    urls:
    - charts/kube-prometheus-stack-60.3.0.tgz
    version: 60.3.0
  prometheus-adapter:
  - apiVersion: v1
    appVersion: v0.11.2
    created: "2024-07-05T12:27:38.319342119-07:00"
    description: A Helm chart for k8s prometheus adapter
    digest: 70eca585d84780280de1f6378b40bbae85781125c33d236176aa20d0b906c1d7
    home: https://github.com/kubernetes-sigs/prometheus-adapter
    keywords:
    - hpa
    - metrics
    - prometheus
    - adapter
    maintainers:
    - email: mattias.gees@jetstack.io
      name: mattiasgees
    - name: steven-sheehy
    - email: hfernandez@mesosphere.com
      name: hectorj2f
    name: prometheus-adapter
    sources:
    - https://github.com/kubernetes/charts
    - https://github.com/kubernetes-sigs/prometheus-adapter
    urls:
    - charts/prometheus-adapter-4.10.0.tgz
    version: 4.10.0
generated: "2024-07-05T12:27:38.292475813-07:00"
