apiVersion: v2
name: deepgram-aiworks
type: application
version: 0.1.0
appVersion: "0.3.0"
description: A Helm chart for deploying VoiceWorks (AIWorks) self-hosted alongside or independent of the Deepgram speech distribution.
home: https://developers.deepgram.com/docs/aiworks-self-hosted
sources:
  - https://github.com/deepgram/self-hosted-resources
  - https://github.com/deepgram/voiceworks
kubeVersion: ">=1.28.0-0"
maintainers:
  - name: Deepgram Self-Hosted
    email: self.hosted@deepgram.com
keywords:
  - voice ai
  - aiworks
  - voiceworks
  - flows
  - self-hosted
icon: https://www.dropbox.com/scl/fi/v4jtfbsrx881pbevcga3j/D-icon-black-square-250x250.png?rlkey=barv5jeuhd7t2lczz0m3nane7&dl=1
