{{- $engineTypes := list }}
{{- if .Values.agent.enabled }}
  {{- $engineTypes = list "stt" "tts" "eot" }}
{{- else }}
  {{- $engineTypes = list "" }}
{{- end }}
{{- range $type := $engineTypes }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.engine.namePrefix }}{{- if $type }}-{{ $type }}{{- end }}-metrics
  labels:
{{ include "deepgram-self-hosted.labels" $ | indent 4}}
    app: deepgram-engine
    {{- if $type }}
    engine-type: {{ $type }}
    {{- end }}
    {{- range $key, $val := $.Values.engine.additionalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
spec:
  selector:
    app: deepgram-engine
    {{- if $type }}
    engine-type: {{ $type }}
    {{- end }}
    {{ include "deepgram-self-hosted.selectorLabels" $ }}
  type: NodePort
  ports:
    - name: "metrics"
      port: {{ $.Values.engine.metricsServer.port }}
      targetPort: {{ $.Values.engine.metricsServer.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.engine.namePrefix }}{{- if $type }}-{{ $type }}{{- end }}-internal
  labels:
{{ include "deepgram-self-hosted.labels" $ | indent 4}}
    app: deepgram-engine
    {{- if $type }}
    engine-type: {{ $type }}
    {{- end }}
    {{- range $key, $val := $.Values.engine.additionalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
spec:
  selector:
    app: deepgram-engine
    {{- if $type }}
    engine-type: {{ $type }}
    {{- end }}
    {{ include "deepgram-self-hosted.selectorLabels" $ }}
  ports:
    - name: "primary"
      port: {{ $.Values.engine.server.port }}
      targetPort: {{ $.Values.engine.server.port }}
{{- end }}
