version: 2.1

# Setup configuration to generate dynamic pipeline parameters
setup: true

orbs:
  continuation: circleci/continuation@0.3.1
  vfcommon: voiceflow/common@0.83.1

workflows:
  generate-config:
    jobs:
      - generate-config:
          context: dev-test

jobs:
  generate-config:
    executor: vfcommon/default-executor
    steps:
      - checkout
      - vfcommon/get_changed_files
      - vfcommon/check_commit_message:
          commit_message: "[pre-release]"
          match_env_var: IS_PRERELEASE
          should_halt: false
      - vfcommon/helm-get-modified-charts:
          modified_charts_env_var: MODIFIED_CHARTS
          chart_directory: .
      - run:
          name: Set parameters
          shell: /bin/bash -o pipefail
          command: |
            echo "{\"modified_charts\": \"${MODIFIED_CHARTS}\", \"is_prerelease\": $IS_PRERELEASE}" > "/tmp/pipeline-parameters.json"
      - continuation/continue:
          configuration_path: ".circleci/continue-config.yml"
          parameters: "/tmp/pipeline-parameters.json"